---
general:
    logs:
        console:
            level: "debug"
            timestamp: true
            colorize: true
capture:
    proc:
      name: "ffmpeg"
      args:
        "re":  ""
        "i":   "rtmp://stream.sat1bayern.de/live/mp4:Sat1Schedule_01"
        "c:v": "libx264"
        "vf":  "scale=720x576"
        "c:a": "pcm_s16le"
        "ar":  "48000"
        "f":   "nut"
        "y":   ""
        "-":   ""
encoder:
    outputOptions:
          - "-profile:v main"
          - "-preset medium"
          - "-crf 29"
          - "-tune zerolatency"
          - "-g 30"
          - "-ab 96000"
          - "-ar 44100"
          - "-ac 2"
          - "-t 10"
          - "-y"
playout:
    bmdplay:
        "f": "pipe:0"
    ffmpeg:
        toBmdPlay:
            "c:a":      "pcm_s16le"
            "c:v":      "rawvideo"
            "dn":       ""
            "pix_fmt":  "uyvy422"
            "ar":       "48000"
            "f":        "nut"
        toUrl:
            "c:a": "aac"
            "c:v": "libx264"
            "b:a": "128000"
            "crf": "27"
            "profile:v": "main"
            "level": "3.1"
            "f": "flv"
            "strict": "experimental"
            "preset": "medium"
            "tune": "zerolatency"
            "ac": "2"
            "g": "30"
            "ar": "44100"
streamFormats:
        -   id: "hq_hd_1080_rtmp"
            name: "HD 1920x1080 (hq)"
            description: "High quality 1080 HD"
            args:
                "c:a": "aac"
                "c:v": "libx264"
                "b:a": "128000"
                "crf": "26"
                "profile:v": "main"
                "level": "3.1"
                "f": "flv"
                "strict": "experimental"
                "preset": "medium"
                "tune": "zerolatency"
                "ac": "2"
                "g": "30"
                "ar": "48000"
                "pix_fmt": "yuv420p"
                "vf": "scale=hd1080:interl=-1"
        -   id: "lq_hd_1080_rtmp"
            name: "HD 1920x1080 (lq)"
            description: "Lower quality 1080 HD"
            args:
                "c:a": "aac"
                "c:v": "libx264"
                "b:a": "96000"
                "crf": "29"
                "profile:v": "main"
                "level": "3.1"
                "f": "flv"
                "strict": "experimental"
                "preset": "medium"
                "tune": "zerolatency"
                "ac": "2"
                "g": "30"
                "ar": "44100"
                "pix_fmt": "yuv420p"
                "vf": "scale=hd1080:interl=-1"
        -   id: "hq_hd_720_rtmp"
            name: "HD 1280x720 (hq)"
            description: "High quality 720 HD"
            args:
                "c:a": "aac"
                "c:v": "libx264"
                "b:a": "128000"
                "crf": "26"
                "profile:v": "main"
                "level": "3.1"
                "f": "flv"
                "strict": "experimental"
                "preset": "medium"
                "tune": "zerolatency"
                "ac": "2"
                "g": "30"
                "ar": "48000"
                "pix_fmt": "yuv420p"
                "vf": "scale=hd720:interl=-1"
        -   id: "lq_hd_720_rtmp"
            name: "HD 1280x720 (lq)"
            description: "Lower quality 720 HD"
            args:
                "c:a": "aac"
                "c:v": "libx264"
                "b:a": "96000"
                "crf": "29"
                "profile:v": "main"
                "level": "3.1"
                "f": "flv"
                "strict": "experimental"
                "preset": "medium"
                "tune": "zerolatency"
                "ac": "2"
                "g": "30"
                "ar": "44100"
                "pix_fmt": "yuv420p"
                "vf": "scale=hd720:interl=-1"
        -   id: "hq_pal_rtmp"
            name: "SD PAL (hq)"
            description: "High quality PAL SD"
            args:
                "c:a": "aac"
                "c:v": "libx264"
                "b:a": "128000"
                "crf": "26"
                "profile:v": "main"
                "level": "3.1"
                "f": "flv"
                "strict": "experimental"
                "preset": "medium"
                "tune": "zerolatency"
                "ac": "2"
                "g": "30"
                "ar": "48000"
                "pix_fmt": "yuv420p"
                "vf": "scale=pal:interl=-1"

browser:
    enabled: true
    port: 4000
